apiVersion: v2
name: opensearch-stack
description: A Helm chart for opensearch-stack
kubeVersion: '>=1.15.3'
type: application
version: 0.1.0
dependencies:
- name: opensearch
  alias: opensearch
  version: 3.0.0
  condition: opensearch.enabled
  repository: https://opensearch-project.github.io/helm-charts/
- name: opensearch-dashboards
  alias: opensearch-dashboards
  version: 3.0.0
  condition: opensearch-dashboards.enabled
  repository: https://opensearch-project.github.io/helm-charts/
